### PR TITLE
Basic UI that allows staking but with minimal/poor user experience

### PR DESCRIPTION
**Pull request by shelbyd**
@nikoladimitroff Let me know how you'd like to verify this. I can make a build that points at the devnet and do the necessary chain setup there. Or I could record a video of me using this against a local environment.

This is good enough to deploy with, but not a great UX. It notably doesn't show estimated distribution (as that's non-trivial to calculate and is likely to change from when the user sees it). We can deploy with or without that feature.

#192

### CODE REVIEW

**Comment by nikoladimitroff** [comment]
@shelbyd Let's do a video

**Comment by shelbyd** [comment]
Video of most of the relevant flow (actual unstaking didn't capture because linux screen recording...): https://drive.google.com/file/d/1GWTm6rkWJdX5Q0CM9JuM4Jvz_wbaOPWr/view?usp=sharing

Image showing amount unstaked: https://drive.google.com/file/d/1FQ4VJS4sQw95FpTziDbEWj3zM_OKS1g4/view?usp=sharing

**Comment by nikoladimitroff** [comment]
@shelbyd
* counting time in blocks is bad for UX, let's put in weeks instead; this might not be technically accurate but it is much better for the user
* the radiobutton in the UI that says "25 for 100 shares", etc. needs to become "2 weeks for 100 distribution shares (?)" - the (?) being a hover button with an explanation of the shares; I can share a text for that a bit later

**Comment by shelbyd** [comment]
@nikoladimitroff Want me to do this in the same PR? It will make the review a bit more complex for you.

Note to me:
- [x] Hide staking button if staking not available.

**Comment by shelbyd** [comment]
@nikoladimitroff Screenshot of latest changes: https://drive.google.com/file/d/1yjUx99xtG70FJbtNtdADScphSLYj5tVE/view?usp=sharing

**Review by nikoladimitroff — APPROVED** [review]

**Pull request merged**
